### ISSUE TITLE
Leaves terminal in random text color when I ctrl-C

### ISSUE THREAD

**Issue by natefinch** [ayang64/interfere#1]
Using iTerm2 on Mac, if I run it and then ctrl-C, the text color of my terminal is left in a random color.

**Comment by ayang64** [comment]
Fixed in latest version . Interfere now handles SIGINT and hopefully sends the proper escape sequence to restore the terminal on exit.  Thank you for your bug report.  Please consider upgrading to the enterprise edition for enhanced features and support.
